name: Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      issues: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: "${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get release version
        id: release-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b
        with:
          path: packages/core

      - name: Evaluate next release version
        run: pnpm version-packages

      - name: Get next release version
        id: next-release-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b
        with:
          path: packages/core

      - name: Reset changes
        run: git checkout .

      - name: Modify "workspaces" value in package.json
        run: sed -e "s;packages/core;dist/packages/core;g" package.json > package-new.json && mv package-new.json package.json

      - name: Create Release Pull Request or Publish to npm
        uses: dotansimha/changesets-action@069996e9be15531bd598272996fa23853d61590e
        with:
          title: "release: v${{ steps.next-release-version.outputs.current-version }}"
          commit: "release: v${{ steps.next-release-version.outputs.current-version }}"
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          version: pnpm version-packages-update-lockfile
          createGithubReleases: aggregate
          githubReleaseName: v${{ steps.release-version.outputs.current-version }}
          githubTagName: v${{ steps.release-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
